setup: Use packaging version <22
Same locking version is used in requirements. If we do not lock,
the 22.0 removed Legacy version, see the error:
`ImportError: cannot import name 'LegacyVersion' from 'packaging.version'`

Signed-off-by: Martin Kojtal <martin.kojtal@arm.com>